# Web App Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deploy
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: joelsmith2019/auction-web-app:kube
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: tls-secret
          mountPath: "/etc/ssl/tag"
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
      volumes:
      - name: tls-secret
        secret:
          secretName: tls-secret
          items:
            - key: tls.crt
              path: ssl.crt
            - key: tls.key
              path: ssl.key
---
# Web App Service
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  selector:
    app: web-app
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  type: ClusterIP