# Account DB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-db-deploy
  labels:
    app: account-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-db
  template:
    metadata:
      labels:
        app: account-db
    spec:
      containers:
      - name: account-db
        image: joelsmith2019/account-db:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        env:
          - name: DB_NAME
            value: "account"
          - name: DROP_BOX_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: dropbox-secrets
                key: DROP_BOX_CLIENT_ID
          - name: DROP_BOX_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: dropbox-secrets
                key: DROP_BOX_CLIENT_SECRET
          - name: DROP_BOX_REFRESH_TOKEN
            valueFrom:
              secretKeyRef:
                name: dropbox-secrets
                key: DROP_BOX_REFRESH_TOKEN
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
---
# Account DB Service
apiVersion: v1
kind: Service
metadata:
  name: account-db-service
spec:
  selector:
    app: account-db
  ports:
  - name: postgres-port
    port: 5432
    targetPort: 5432
  type: ClusterIP