# Activity DB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity-db-deploy
  labels:
    app: activity-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activity-db
  template:
    metadata:
      labels:
        app: activity-db
    spec:
      containers:
      - name: activity-db
        image: joelsmith2019/activity-db:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        env:
          - name: DB_NAME
            value: "activity"
          - name: DROP_BOX_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: dropbox-secrets
                key: DROP_BOX_CLIENT_ID
          - name: DROP_BOX_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: dropbox-secrets
                key: DROP_BOX_CLIENT_SECRET
          - name: DROP_BOX_REFRESH_TOKEN
            valueFrom:
              secretKeyRef:
                name: dropbox-secrets
                key: DROP_BOX_REFRESH_TOKEN
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
# Activity DB Service
apiVersion: v1
kind: Service
metadata:
  name: activity-db-service
spec:
  selector:
    app: activity-db
  ports:
  - name: postgres-port
    port: 5432
    targetPort: 5432
  type: ClusterIP